# Generated by Django 5.2.13 on 2026-04-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ITDASReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(choices=[('wheat', 'Wheat'), ('tomato', 'Tomato'), ('olive', 'Olive'), ('date_palm', 'Date Palm'), ('potato', 'Potato'), ('onion', 'Onion'), ('pepper', 'Pepper'), ('watermelon', 'Watermelon'), ('citrus', 'Citrus'), ('barley', 'Barley')], max_length=20)),
                ('growth_stage', models.CharField(choices=[('germination', 'Germination'), ('vegetative', 'Vegetative'), ('flowering', 'Flowering'), ('fruiting', 'Fruiting'), ('maturation', 'Maturation')], max_length=20)),
                ('npk_n', models.FloatField(help_text='Nitrogen kg per hectare')),
                ('npk_p', models.FloatField(help_text='Phosphorus kg per hectare')),
                ('npk_k', models.FloatField(help_text='Potassium kg per hectare')),
                ('irrigation_liters_per_ha_per_day', models.FloatField(help_text='Daily irrigation liters per hectare')),
            ],
            options={
                'unique_together': {('crop', 'growth_stage')},
            },
        ),
    ]
